version: '3.8'
services:
  otel-collector:
    image: otel/opentelemetry-collector:latest
    volumes:
      - ./collector:/etc/collector
    command: ["--config", "/etc/collector/otel-collector-config.yaml"]
    ports:
      - "4317:4317"  # OTLP gRPC
      - "8889:8889"  # Prometheus exporter