receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:

processors:
  resource: # Resource spec https://opentelemetry.io/docs/specs/semconv/resource/
    attributes:
      - action: insert
        key: loki.format
        value: json
      - action: insert
        key: loki.resource.labels
        value: service.name, app, runtime
  
  batch:
    timeout: 1s
    send_batch_size: 1024

exporters:  
  prometheus:
    endpoint: ":9201"
    send_timestamps: true
    metric_expiration: 180m
    enable_open_metrics: true
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true      
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    tls:
      insecure: true  

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      exporters: [ otlp ]
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
    logs:
      receivers: [ otlp ]
     # processors: [ batch, resource ]
      exporters: [ loki ]