receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:

exporters:  
  prometheus:
    endpoint: ":9201"
    send_timestamps: true
    metric_expiration: 180m
    enable_open_metrics: true
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true
  

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      exporters: [ otlp ]
    metrics:
      receivers: [otlp]
      exporters: [prometheus]